version: "3.7"
services:
  node:
    build:
      context: docker/node
      target: ${ENVIRONMENT:-production-pseudo}
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached

  playground:
    build:
      context: docker/playground
      target: ${ENVIRONMENT:-production-pseudo}
    ports:
      - 4000:4000
    volumes:
      - .:/app:cached